# Clustering algorithm

Import the packages necessary to read the datasets from disk and set the base path of the datasets

In [1]:
import pandas as pd
import pathlib
import os

base_path = pathlib.Path(os.environ.get("SAMPLES_DIR", ""))

Read the input dataset containing all the data for the clustering problem

In [9]:
clustering_df = pd.read_csv(
    base_path / "clustering" / "G_140_AMELIA_zoning.csv",
    sep=';')

In [10]:
clustering_df[clustering_df['popolazion'].notna()].head()

,ID,popolazion,geometry,usable,beds,personnel,density
0,ARCONATE,68.24,"POLYGON ((487010.785388 5044903.977341, 487010...",NaN,NaN,NaN,0.081721
1,MAGNAGO,95.08,"POLYGON ((484328.912806 5049867.38367, 484328....",NaN,NaN,NaN,0.083897
2,INVERUNO,84.44,"POLYGON ((485634.28175 5041541.041653, 485634....",NaN,NaN,NaN,0.069290
3,BUSCATE,46.80,"POLYGON ((485631.5327 5041538.040956, 485631.5...",NaN,NaN,NaN,0.060276
4,BUSTO GAROLFO,140.42,"POLYGON ((490165.729427 5045231.428402, 490165...",NaN,NaN,NaN,0.109699

In [11]:
clustering_df[clustering_df['personnel'].notna()].head()

Empty DataFrame
Columns: [ID, popolazion, geometry, usable, beds, personnel, density]
Index: []

In [2]:
from libadalina_core.sedona_utils import EPSGFormats
from clustering.algorithms import clustering_algorithm
from clustering.models.adalina_zoning_distance import ClusteringDistance

clustering_solution = clustering_algorithm(
    clustering_df,
    epsg=EPSGFormats.EPSG32632,
    k_min=4,
    k_max=6,
    distances=[
        ClusteringDistance(name="popolazion", weight=2, function="chebyshev"),
        ClusteringDistance(name="density", function="euclidean"),
        ClusteringDistance(name="geometry"),
    ],
)

clustering_solution.get_dataframe_to_export().head()

Running HiGHS 1.11.0 (git hash: n/a): Copyright (c) 2025 HiGHS under MIT licence terms
MIP  has 4331 rows; 590 cols; 13367 nonzeros; 590 integer variables (590 binary)
Coefficient ranges:
  Matrix [1e+00, 1e+00]
  Cost   [2e-02, 4e-01]
  Bound  [1e+00, 1e+00]
  RHS    [1e+00, 6e+00]
WARNING: User-supplied values fix only 51 / 590 discrete variables, so attempt to complete a feasible solution may be expensive
Coefficient ranges:
  Matrix [1e+00, 1e+00]
  Cost   [2e-02, 4e-01]
  Bound  [1e+00, 1e+00]
  RHS    [1e+00, 6e+00]
Presolving model
Presolve: Infeasible

Src: B => Branching; C => Central rounding; F => Feasibility pump; J => Feasibility jump;
     H => Heuristic; L => Sub-MIP; P => Empty MIP; R => Randomized rounding; Z => ZI Round;
     I => Shifting; S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution;
     z => Trivial zero; l => Trivial lower; u => Trivial upper; p => Trivial point

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   -inf            inf                  inf        0      0      0         0     0.0s

Solving report
  Status            Infeasible
  Primal bound      inf
  Dual bound        -inf
  Gap               inf
  P-D integral      0
  Solution status   -
  Timing            0.00 (total)
                    0.00 (presolve)
                    0.00 (solve)
                    0.00 (postsolve)
  Max sub-MIP depth 0
  Nodes             0
  Repair LPs        0 (0 feasible; 0 iterations)
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
Presolving model
4331 rows, 590 cols, 13367 nonzeros  0s
4331 rows, 590 cols, 13367 nonzeros  0s

Solving MIP model with:
   4331 rows
   590 cols (590 binary, 0 integer, 0 implied int., 0 continuous, 0 domain fixed)
   13367 nonzeros

Src: B => Branching; C => Central rounding; F => Feasibility pump; J => Feasibility jump;
     H => Heuristic; L => Sub-MIP; P => Empty MIP; R => Randomized rounding; Z => ZI Round;
     I => Shifting; S => Solve LP; T => Evaluate node; U => Unbounded; X => User solution;
     z => Trivial zero; l => Trivial lower; u => Trivial upper; p => Trivial point

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
Src  Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 J       0       0         0   0.00%   -inf            2.215701075        Large        0      0      0         0     0.0s
         0       0         0   0.00%   0.8924665339    2.215701075       59.72%        0      0      8       122     0.1s
 C       0       0         0   0.00%   0.9455857403    2.127058346       55.54%       62     20      8       237     0.1s
 L       0       0         0   0.00%   1.008810593     1.547182779       34.80%     1427     88      8      1252     2.5s
        53       1        25  43.16%   1.008810593     1.547182779       34.80%     1013     64   2493     35215     7.6s
       230       9       108  66.05%   1.016024304     1.547182779       34.33%     1303     90   8686     68181    12.6s
       506      24       240  72.57%   1.018347205     1.547182779       34.18%     2703    101   4951     98204    18.8s
      1071      62       495  73.88%   1.032356755     1.547182779       33.28%     2921    107   8945    124851    23.8s

Restarting search from the root node
Model after restart has 4331 rows, 590 cols (590 bin., 0 int., 0 impl., 0 cont., 0 dom.fix.), and 13367 nonzeros

      1736       0         0   0.00%   1.049169002     1.547182779       32.19%      107      0      0    149363    28.7s
      1736       0         0   0.00%   1.049169002     1.547182779       32.19%      107     60      6    149538    28.7s
      1941       9        96  46.08%   1.049169002     1.547182779       32.19%     2337    102   2671    164422    34.0s
      2917      45       561  57.00%   1.049169002     1.547182779       32.19%     1495    102   8351    188454    39.0s
      3899      89      1023  57.01%   1.068898115     1.547182779       30.91%     1644    104   9051    211733    44.0s
      4782     124      1440  57.03%   1.081764872     1.547182779       30.08%     2993    101   9310    235841    49.0s
      5646     149      1855  75.27%   1.081764872     1.547182779       30.08%     4324    109   9144    258096    54.1s
      6427     174      2230  75.35%   1.109967053     1.547182779       28.26%     4452    131   9713    280957    59.1s
      6615     183      2319  75.35%   1.109967053     1.547182779       28.26%     4426    119   9181    285988    60.0s

Solving report
  Status            Time limit reached
  Primal bound      1.54718277863
  Dual bound        1.10996705301
  Gap               28.26% (tolerance: 0.01%)
  P-D integral      19.8590086477
  Solution status   feasible
                    1.54718277863 (objective)
                    0 (bound viol.)
                    5.80276567537e-14 (int. viol.)
                    0 (row viol.)
  Timing            60.00 (total)
                    0.00 (presolve)
                    0.00 (solve)
                    0.00 (postsolve)
  Max sub-MIP depth 3
  Nodes             6615
  Repair LPs        0 (0 feasible; 0 iterations)
  LP iterations     285988 (total)
                    123788 (strong br.)
                    7270 (separation)
                    15773 (heuristics)

,ID,popolazion,geometry,usable,beds,personnel,density,zoning_Adalina
0,ROBECCHETTO CON INDUNO,47.95,"POLYGON ((480748.825 5043027.556, 480748.825 5...",NaN,NaN,NaN,0.034325,6
1,NOSATE,6.44,"POLYGON ((477387.977 5043229.078, 477387.977 5...",NaN,NaN,NaN,0.013081,18
2,BERNATE TICINO,29.41,"POLYGON ((487458.22 5036059.092, 487458.22 503...",NaN,NaN,NaN,0.024243,10
3,CUGGIONO,80.79,"POLYGON ((486991.876 5038856.062, 486991.876 5...",NaN,NaN,NaN,0.054359,6
4,TURBIGO,71.06,"POLYGON ((480748.826 5043027.557, 480748.826 5...",NaN,NaN,NaN,0.083216,6